name: Another Workflow (Runs on Push/Pull)
permissions:
    contents: write   # This is required to create/push the new git tag
on:
  # Runs on push events to any branch
  push:
    branches: [ '**' ]  
  # Runs on pull request events
  pull_request:

  # Allows manual triggering and accepts optional inputs
  workflow_dispatch:
    inputs:
      HELIOS_TRIGGERED_BY:
        description: "Optional value for HELIOS_TRIGGERED_BY"
        required: false
        default: ""
      HELIOS_BRANCH_NAME:
        description: "Optional value for HELIOS_BRANCH_NAME"
        required: false
        default: ""
      HELIOS_BRANCH_HEAD_SHA:
        description: "Optional value for HELIOS_BRANCH_NAME"
        required: false
        default: ""
      HELIOS_ENVIRONMENT_NAME:
        description: "Optional value for HELIOS_ENVIRONMENT_NAME"
        required: false
        default: ""
      HELIOS_RAW_URL:
        description: "Optional value for HELIOS_ENVIRONMENT_NAME"
        required: false
        default: ""
      HELIOS_BUILD:
        description: "Optional value for HELIOS_BUILD"
        required: false
        default: ""
      HELIOS_BUILD_TAG:
        description: "Optional value for HELIOS_BUILD_TAG"
        required: false
        default: ""
      HELIOS_PR_NUMBER:
        description: "Optional value for HELIOS_BUILD_TAG"
        required: false
        default: ""

jobs:
  greet:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Echo parameters (only if they exist)
        run: |
          [[ -n "${{ github.event.inputs.HELIOS_TRIGGERED_BY }}" ]] && echo "HELIOS_TRIGGERED_BY: ${{ github.event.inputs.HELIOS_TRIGGERED_BY }}"
          [[ -n "${{ github.event.inputs.HELIOS_BRANCH_NAME }}" ]] && echo "HELIOS_BRANCH_NAME: ${{ github.event.inputs.HELIOS_BRANCH_NAME }}"
          [[ -n "${{ github.event.inputs.HELIOS_BRANCH_HEAD_SHA }}" ]] && echo "HELIOS_BRANCH_HEAD_SHA: ${{ github.event.inputs.HELIOS_BRANCH_HEAD_SHA }}"
          [[ -n "${{ github.event.inputs.HELIOS_ENVIRONMENT_NAME }}" ]] && echo "HELIOS_ENVIRONMENT_NAME: ${{ github.event.inputs.HELIOS_ENVIRONMENT_NAME }}"
          [[ -n "${{ github.event.inputs.HELIOS_RAW_URL }}" ]] && echo "HELIOS_RAW_URL: ${{ github.event.inputs.HELIOS_RAW_URL }}"
          [[ -n "${{ github.event.inputs.HELIOS_BUILD }}" ]] && echo "HELIOS_BUILD: ${{ github.event.inputs.HELIOS_BUILD }}"
          [[ -n "${{ github.event.inputs.HELIOS_BUILD_TAG }}" ]] && echo "HELIOS_BUILD_TAG: ${{ github.event.inputs.HELIOS_BUILD_TAG }}"
          [[ -n "${{ github.event.inputs.HELIOS_PR_NUMBER }}" ]] && echo "HELIOS_PR_NUMBER: ${{ github.event.inputs.HELIOS_PR_NUMBER }}"
