# This is a basic workflow that is manually triggered

name: Another Workflow (Runs on Push/Pull)

# Controls when the action will run. Workflow runs on push and pull request events.
on:
  # Runs on push events to any branch
  push:
    branches: [ '**' ]  # This triggers on all branches

  # Runs on pull request events
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    environment: prod
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
